## Author: Jose Lazarte
## Date: 4/3/2020
## CS301-006, Professor Watson
## HW06 Solution

The purpose of this assignment is to help students practice using Python to prepare their data sets for machine learning.

link to the git repo:

In [1]:
import pandas as pd
import numpy as np

#### Question 1 - Read in the data set and print the % empty values for each column. Are there any columns with missing values?

In [2]:
data_dir = 'groundhog.csv'

In [3]:
ground_df = pd.read_csv(data_dir)

In [4]:
new_df = ground_df.isnull().sum()

In [5]:
col_names = ground_df.columns
print('Empty percent %:')
for i in range(len(col_names)):
    if i != 0:
        percent = (new_df[i]/ground_df.count()[i])*100
        print(col_names[i],percent)

Empty percent %:
Year 0.0
Punxsutawney Phil 0.0
February Average Temperature 7.377049180327869
February Average Temperature (Northeast) 7.377049180327869
February Average Temperature (Midwest) 7.377049180327869
February Average Temperature (Pennsylvania) 7.377049180327869
March Average Temperature 7.377049180327869
March Average Temperature (Northeast) 7.377049180327869
March Average Temperature (Midwest) 7.377049180327869
March Average Temperature (Pennsylvania) 7.377049180327869

#### Question 2 - Create a new dataframe which is a copy of the orginal one. In this copy, replace the missing values in the data set using one of the discussed methods in class.

In [6]:
new_ground = ground_df.fillna(ground_df.mean()).drop(['Unnamed: 0'], axis=1)

In [7]:
new_ground

,Year,Punxsutawney Phil,February Average Temperature,February Average Temperature (Northeast),February Average Temperature (Midwest),February Average Temperature (Pennsylvania),March Average Temperature,March Average Temperature (Northeast),March Average Temperature (Midwest),March Average Temperature (Pennsylvania)
0,1886,No Record,33.802705,22.693443,32.694262,26.522951,41.699016,32.368033,42.568852,35.908197
1,1887,Full Shadow,33.802705,22.693443,32.694262,26.522951,41.699016,32.368033,42.568852,35.908197
2,1888,Full Shadow,33.802705,22.693443,32.694262,26.522951,41.699016,32.368033,42.568852,35.908197
3,1889,No Record,33.802705,22.693443,32.694262,26.522951,41.699016,32.368033,42.568852,35.908197
4,1890,No Shadow,33.802705,22.693443,32.694262,26.522951,41.699016,32.368033,42.568852,35.908197
5,1891,No Record,33.802705,22.693443,32.694262,26.522951,41.699016,32.368033,42.568852,35.908197
6,1892,No Record,33.802705,22.693443,32.694262,26.522951,41.699016,32.368033,42.568852,35.908197
7,1893,No Record,33.802705,22.693443,32.694262,26.522951,41.699016,32.368033,42.568852,35.908197
8,1894,No Record,33.802705,22.693443,32.694262,26.522951,41.699016,32.368033,42.568852,35.908197
9,1895,No Record,26.600000,15.600000,21.900000,17.000000,39.970000,27.600000,40.200000,31.300000
10,1896,No Record,35.040000,22.200000,33.500000,26.600000,38.030000,25.300000,36.900000,27.800000
11,1897,No Record,33.390000,23.600000,34.700000,27.900000,38.790000,32.000000,44.000000,36.900000
12,1898,Full Shadow,35.370000,24.800000,33.300000,26.700000,41.050000,38.000000,46.000000,42.000000
13,1899,No Record,25.500000,18.100000,22.200000,20.000000,37.630000,29.300000,38.400000,34.000000
14,1900,Full Shadow,30.760000,21.400000,27.500000,24.100000,41.270000,26.000000,37.900000,29.300000
15,1901,Full Shadow,29.860000,16.000000,26.200000,18.900000,40.710000,30.800000,41.900000,35.100000
16,1902,No Record,31.460000,20.100000,23.600000,21.000000,41.580000,37.100000,43.900000,38.800000
17,1903,Full Shadow,28.420000,24.500000,31.300000,28.000000,42.210000,40.400000,47.700000,44.500000
18,1904,Full Shadow,31.590000,15.000000,28.200000,19.200000,41.760000,29.800000,42.800000,34.000000
19,1905,Full Shadow,26.940000,15.200000,22.200000,18.100000,45.120000,31.400000,47.200000,36.900000
20,1906,Full Shadow,33.690000,22.000000,30.700000,25.300000,36.100000,25.700000,33.900000,29.100000
21,1907,Full Shadow,35.460000,15.200000,31.500000,20.100000,45.700000,33.300000,50.200000,39.500000
22,1908,Full Shadow,33.010000,18.400000,31.200000,22.100000,43.920000,32.700000,47.100000,38.400000
23,1909,Full Shadow,35.020000,26.400000,37.200000,32.900000,40.350000,29.600000,41.100000,33.100000
24,1910,Full Shadow,29.300000,20.600000,28.500000,23.800000,49.440000,37.800000,51.900000,42.600000
25,1911,Full Shadow,33.660000,21.400000,37.500000,28.500000,44.020000,28.400000,42.900000,32.800000
26,1912,Full Shadow,31.080000,18.600000,25.800000,21.100000,35.760000,27.700000,35.200000,31.500000
27,1913,Full Shadow,29.500000,20.200000,29.600000,25.000000,38.710000,35.900000,41.100000,40.000000
28,1914,Full Shadow,29.520000,14.500000,26.300000,18.700000,40.750000,29.600000,39.000000,31.700000
29,1915,Full Shadow,35.940000,26.700000,37.600000,30.600000,36.950000,28.300000,34.900000,30.300000
...,...,...,...,...,...,...,...,...,...,...
101,1987,Full Shadow,37.380000,21.800000,36.900000,26.800000,42.570000,35.500000,45.800000,39.000000
102,1988,No Shadow,33.690000,23.700000,30.400000,26.800000,42.400000,33.200000,43.000000,37.200000
103,1989,Full Shadow,29.170000,23.000000,28.600000,27.100000,42.670000,31.800000,44.000000,36.700000
104,1990,No Shadow,36.700000,28.000000,39.900000,33.900000,44.740000,35.700000,46.600000,40.200000
105,1991,Full Shadow,39.810000,28.700000,37.400000,32.400000,43.320000,36.100000,46.100000,39.500000
106,1992,Full Shadow,39.700000,25.700000,39.500000,30.900000,44.710000,30.000000,44.000000,34.500000
107,1993,Full Shadow,31.140000,17.500000,30.500000,23.500000,41.790000,29.800000,39.500000,32.800000
108,1994,Full Shadow,31.870000,19.400000,32.400000,24.100000,44.510000,31.600000,42.900000,33.800000
109,1995,No Shadow,37.360000,20.600000,32.600000,23.900000,43.340000,36.200000,45.600000,39.700000
110,1996,Full Shadow,35.690000,23.600000,33.400000,27.000000,39.020000,29.700000,37.200000,31.800000
111,1997,No Shadow,36.050000,28.600000,37.700000,33.000000,44.670000,32.100000,45.800000,37.600000
112,1998,Full Shadow,38.710000,31.600000,40.900000,35.800000,41.340000,36.200000,42.900000,39.700000
113,1999,No Shadow,39.490000,28.200000,39.500000,31.700000,42.800000,33.000000,39.800000,34.200000
114,2000,Full Shadow,39.780000,27.200000,40.100000,31.600000,46.040000,39.100000,47.700000,42.600000
115,2001,Full Shadow,33.980000,26.000000,36.100000,31.500000,41.490000,30.200000,39.300000,33.300000
116,2002,Full Shadow,36.390000,29.700000,36.800000,33.900000,39.540000,34.700000,41.500000,38.200000
117,2003,Full Shadow,32.790000,20.000000,30.200000,23.800000,43.300000,32.900000,44.800000,37.200000
118,2004,Full Shadow,33.570000,24.000000,33.100000,27.000000,47.410000,35.900000,47.000000,39.500000
119,2005,Full Shadow,37.940000,26.200000,38.100000,30.100000,42.310000,29.700000,40.800000,32.300000
120,2006,Full Shadow,34.830000,26.200000,33.700000,29.800000,42.620000,34.000000,43.800000,37.000000
121,2007,No Shadow,32.410000,18.000000,26.100000,20.100000,47.660000,32.700000,50.100000,37.400000
122,2008,Full Shadow,34.700000,25.400000,32.100000,27.700000,41.860000,31.600000,42.000000,35.600000
123,2009,Full Shadow,36.770000,26.200000,35.900000,29.600000,42.870000,34.100000,45.700000,38.200000
124,2010,Full Shadow,31.800000,25.900000,28.200000,25.800000,43.570000,39.600000,44.600000,42.000000
125,2011,No Shadow,33.040000,24.100000,34.400000,28.600000,43.070000,33.000000,44.200000,36.300000
126,2012,Full Shadow,37.510000,30.600000,38.600000,34.300000,50.410000,43.400000,56.300000,47.700000
127,2013,No Shadow,34.770000,25.300000,33.400000,27.400000,40.910000,32.700000,37.300000,33.900000
128,2014,Full Shadow,32.130000,21.000000,27.100000,22.800000,40.510000,26.000000,38.000000,30.300000
129,2015,Full Shadow,32.990000,12.100000,23.400000,16.100000,45.390000,27.800000,41.600000,31.600000
130,2016,No Shadow,39.470000,28.100000,36.900000,30.800000,47.500000,38.800000,49.500000,43.400000

#### Question 3 - Is your proposed method from Question 2 appropriate in this case? Why or why not?

Yes my method is appropriate as the empty percentage across the Null rows is less than 60%, therefore, replacing these rows with the mean will not harm the values in the end.

#### Question 4 - Using the original dataframe (unchanged from Questoins 2, 3), create a mapping for the "Punxsutawney Phil" column which changes the categories into numerical quantities. For example: 'No Record' can be 0, 'No Shadow' can be 1, 'Partial Shadow' can be 2, and 'Full Shadow' can be 3. You should create the mapping *and* apply it to the data set by adding a new column called "Shadow".

In [8]:
sha_rec = {'No Record':0,'No Shadow':1,'Partial Shadow':2,'Full Shadow':3}
ground_df['Shadow'] = ground_df['Punxsutawney Phil'].map(sha_rec)
ground_df = ground_df.drop(['Unnamed: 0'], axis=1)

In [9]:
ground_df

,Year,Punxsutawney Phil,February Average Temperature,February Average Temperature (Northeast),February Average Temperature (Midwest),February Average Temperature (Pennsylvania),March Average Temperature,March Average Temperature (Northeast),March Average Temperature (Midwest),March Average Temperature (Pennsylvania),Shadow
0,1886,No Record,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1887,Full Shadow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
2,1888,Full Shadow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
3,1889,No Record,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,1890,No Shadow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
5,1891,No Record,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
6,1892,No Record,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
7,1893,No Record,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
8,1894,No Record,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
9,1895,No Record,26.60,15.6,21.9,17.0,39.97,27.6,40.2,31.3,0
10,1896,No Record,35.04,22.2,33.5,26.6,38.03,25.3,36.9,27.8,0
11,1897,No Record,33.39,23.6,34.7,27.9,38.79,32.0,44.0,36.9,0
12,1898,Full Shadow,35.37,24.8,33.3,26.7,41.05,38.0,46.0,42.0,3
13,1899,No Record,25.50,18.1,22.2,20.0,37.63,29.3,38.4,34.0,0
14,1900,Full Shadow,30.76,21.4,27.5,24.1,41.27,26.0,37.9,29.3,3
15,1901,Full Shadow,29.86,16.0,26.2,18.9,40.71,30.8,41.9,35.1,3
16,1902,No Record,31.46,20.1,23.6,21.0,41.58,37.1,43.9,38.8,0
17,1903,Full Shadow,28.42,24.5,31.3,28.0,42.21,40.4,47.7,44.5,3
18,1904,Full Shadow,31.59,15.0,28.2,19.2,41.76,29.8,42.8,34.0,3
19,1905,Full Shadow,26.94,15.2,22.2,18.1,45.12,31.4,47.2,36.9,3
20,1906,Full Shadow,33.69,22.0,30.7,25.3,36.10,25.7,33.9,29.1,3
21,1907,Full Shadow,35.46,15.2,31.5,20.1,45.70,33.3,50.2,39.5,3
22,1908,Full Shadow,33.01,18.4,31.2,22.1,43.92,32.7,47.1,38.4,3
23,1909,Full Shadow,35.02,26.4,37.2,32.9,40.35,29.6,41.1,33.1,3
24,1910,Full Shadow,29.30,20.6,28.5,23.8,49.44,37.8,51.9,42.6,3
25,1911,Full Shadow,33.66,21.4,37.5,28.5,44.02,28.4,42.9,32.8,3
26,1912,Full Shadow,31.08,18.6,25.8,21.1,35.76,27.7,35.2,31.5,3
27,1913,Full Shadow,29.50,20.2,29.6,25.0,38.71,35.9,41.1,40.0,3
28,1914,Full Shadow,29.52,14.5,26.3,18.7,40.75,29.6,39.0,31.7,3
29,1915,Full Shadow,35.94,26.7,37.6,30.6,36.95,28.3,34.9,30.3,3
...,...,...,...,...,...,...,...,...,...,...,...
101,1987,Full Shadow,37.38,21.8,36.9,26.8,42.57,35.5,45.8,39.0,3
102,1988,No Shadow,33.69,23.7,30.4,26.8,42.40,33.2,43.0,37.2,1
103,1989,Full Shadow,29.17,23.0,28.6,27.1,42.67,31.8,44.0,36.7,3
104,1990,No Shadow,36.70,28.0,39.9,33.9,44.74,35.7,46.6,40.2,1
105,1991,Full Shadow,39.81,28.7,37.4,32.4,43.32,36.1,46.1,39.5,3
106,1992,Full Shadow,39.70,25.7,39.5,30.9,44.71,30.0,44.0,34.5,3
107,1993,Full Shadow,31.14,17.5,30.5,23.5,41.79,29.8,39.5,32.8,3
108,1994,Full Shadow,31.87,19.4,32.4,24.1,44.51,31.6,42.9,33.8,3
109,1995,No Shadow,37.36,20.6,32.6,23.9,43.34,36.2,45.6,39.7,1
110,1996,Full Shadow,35.69,23.6,33.4,27.0,39.02,29.7,37.2,31.8,3
111,1997,No Shadow,36.05,28.6,37.7,33.0,44.67,32.1,45.8,37.6,1
112,1998,Full Shadow,38.71,31.6,40.9,35.8,41.34,36.2,42.9,39.7,3
113,1999,No Shadow,39.49,28.2,39.5,31.7,42.80,33.0,39.8,34.2,1
114,2000,Full Shadow,39.78,27.2,40.1,31.6,46.04,39.1,47.7,42.6,3
115,2001,Full Shadow,33.98,26.0,36.1,31.5,41.49,30.2,39.3,33.3,3
116,2002,Full Shadow,36.39,29.7,36.8,33.9,39.54,34.7,41.5,38.2,3
117,2003,Full Shadow,32.79,20.0,30.2,23.8,43.30,32.9,44.8,37.2,3
118,2004,Full Shadow,33.57,24.0,33.1,27.0,47.41,35.9,47.0,39.5,3
119,2005,Full Shadow,37.94,26.2,38.1,30.1,42.31,29.7,40.8,32.3,3
120,2006,Full Shadow,34.83,26.2,33.7,29.8,42.62,34.0,43.8,37.0,3
121,2007,No Shadow,32.41,18.0,26.1,20.1,47.66,32.7,50.1,37.4,1
122,2008,Full Shadow,34.70,25.4,32.1,27.7,41.86,31.6,42.0,35.6,3
123,2009,Full Shadow,36.77,26.2,35.9,29.6,42.87,34.1,45.7,38.2,3
124,2010,Full Shadow,31.80,25.9,28.2,25.8,43.57,39.6,44.6,42.0,3
125,2011,No Shadow,33.04,24.1,34.4,28.6,43.07,33.0,44.2,36.3,1
126,2012,Full Shadow,37.51,30.6,38.6,34.3,50.41,43.4,56.3,47.7,3
127,2013,No Shadow,34.77,25.3,33.4,27.4,40.91,32.7,37.3,33.9,1
128,2014,Full Shadow,32.13,21.0,27.1,22.8,40.51,26.0,38.0,30.3,3
129,2015,Full Shadow,32.99,12.1,23.4,16.1,45.39,27.8,41.6,31.6,3
130,2016,No Shadow,39.47,28.1,36.9,30.8,47.50,38.8,49.5,43.4,1

#### Question 5 - For all rows which have no record, remove the rows which have empty values in all of the quantitative columns. (Only 9 should be removed.)

In [10]:
ground_df = ground_df.loc[
    (ground_df['February Average Temperature'].notnull())|
    (ground_df['February Average Temperature (Northeast)'].notnull())|
    (ground_df['February Average Temperature (Midwest)'].notnull())|
    (ground_df['February Average Temperature (Pennsylvania)'].notnull())|
    (ground_df['March Average Temperature'].notnull())|
    (ground_df['March Average Temperature (Northeast)'].notnull())|
    (ground_df['March Average Temperature (Midwest)'].notnull())|
    (ground_df['March Average Temperature (Pennsylvania)'].notnull())
]

In [11]:
ground_df

,Year,Punxsutawney Phil,February Average Temperature,February Average Temperature (Northeast),February Average Temperature (Midwest),February Average Temperature (Pennsylvania),March Average Temperature,March Average Temperature (Northeast),March Average Temperature (Midwest),March Average Temperature (Pennsylvania),Shadow
9,1895,No Record,26.60,15.6,21.9,17.0,39.97,27.6,40.2,31.3,0
10,1896,No Record,35.04,22.2,33.5,26.6,38.03,25.3,36.9,27.8,0
11,1897,No Record,33.39,23.6,34.7,27.9,38.79,32.0,44.0,36.9,0
12,1898,Full Shadow,35.37,24.8,33.3,26.7,41.05,38.0,46.0,42.0,3
13,1899,No Record,25.50,18.1,22.2,20.0,37.63,29.3,38.4,34.0,0
14,1900,Full Shadow,30.76,21.4,27.5,24.1,41.27,26.0,37.9,29.3,3
15,1901,Full Shadow,29.86,16.0,26.2,18.9,40.71,30.8,41.9,35.1,3
16,1902,No Record,31.46,20.1,23.6,21.0,41.58,37.1,43.9,38.8,0
17,1903,Full Shadow,28.42,24.5,31.3,28.0,42.21,40.4,47.7,44.5,3
18,1904,Full Shadow,31.59,15.0,28.2,19.2,41.76,29.8,42.8,34.0,3
19,1905,Full Shadow,26.94,15.2,22.2,18.1,45.12,31.4,47.2,36.9,3
20,1906,Full Shadow,33.69,22.0,30.7,25.3,36.10,25.7,33.9,29.1,3
21,1907,Full Shadow,35.46,15.2,31.5,20.1,45.70,33.3,50.2,39.5,3
22,1908,Full Shadow,33.01,18.4,31.2,22.1,43.92,32.7,47.1,38.4,3
23,1909,Full Shadow,35.02,26.4,37.2,32.9,40.35,29.6,41.1,33.1,3
24,1910,Full Shadow,29.30,20.6,28.5,23.8,49.44,37.8,51.9,42.6,3
25,1911,Full Shadow,33.66,21.4,37.5,28.5,44.02,28.4,42.9,32.8,3
26,1912,Full Shadow,31.08,18.6,25.8,21.1,35.76,27.7,35.2,31.5,3
27,1913,Full Shadow,29.50,20.2,29.6,25.0,38.71,35.9,41.1,40.0,3
28,1914,Full Shadow,29.52,14.5,26.3,18.7,40.75,29.6,39.0,31.7,3
29,1915,Full Shadow,35.94,26.7,37.6,30.6,36.95,28.3,34.9,30.3,3
30,1916,Full Shadow,33.03,18.9,30.1,22.8,42.15,24.2,40.2,28.2,3
31,1917,Full Shadow,30.09,17.8,29.1,23.0,38.35,31.2,42.6,35.4,3
32,1918,Full Shadow,33.82,19.8,34.1,25.7,45.75,32.9,48.2,39.3,3
33,1919,Full Shadow,32.25,25.4,34.1,29.6,40.89,34.8,43.9,38.6,3
34,1920,Full Shadow,33.69,19.6,31.5,23.0,40.28,32.7,42.9,36.7,3
35,1921,Full Shadow,36.90,25.1,37.6,30.0,46.63,40.6,51.6,45.4,3
36,1922,Full Shadow,31.95,24.2,35.7,30.1,40.42,33.8,44.1,37.1,3
37,1923,Full Shadow,29.57,16.2,29.1,22.1,38.30,27.9,40.1,34.3,3
38,1924,Full Shadow,35.19,18.3,31.7,23.9,37.18,31.3,37.5,33.5,3
...,...,...,...,...,...,...,...,...,...,...,...
101,1987,Full Shadow,37.38,21.8,36.9,26.8,42.57,35.5,45.8,39.0,3
102,1988,No Shadow,33.69,23.7,30.4,26.8,42.40,33.2,43.0,37.2,1
103,1989,Full Shadow,29.17,23.0,28.6,27.1,42.67,31.8,44.0,36.7,3
104,1990,No Shadow,36.70,28.0,39.9,33.9,44.74,35.7,46.6,40.2,1
105,1991,Full Shadow,39.81,28.7,37.4,32.4,43.32,36.1,46.1,39.5,3
106,1992,Full Shadow,39.70,25.7,39.5,30.9,44.71,30.0,44.0,34.5,3
107,1993,Full Shadow,31.14,17.5,30.5,23.5,41.79,29.8,39.5,32.8,3
108,1994,Full Shadow,31.87,19.4,32.4,24.1,44.51,31.6,42.9,33.8,3
109,1995,No Shadow,37.36,20.6,32.6,23.9,43.34,36.2,45.6,39.7,1
110,1996,Full Shadow,35.69,23.6,33.4,27.0,39.02,29.7,37.2,31.8,3
111,1997,No Shadow,36.05,28.6,37.7,33.0,44.67,32.1,45.8,37.6,1
112,1998,Full Shadow,38.71,31.6,40.9,35.8,41.34,36.2,42.9,39.7,3
113,1999,No Shadow,39.49,28.2,39.5,31.7,42.80,33.0,39.8,34.2,1
114,2000,Full Shadow,39.78,27.2,40.1,31.6,46.04,39.1,47.7,42.6,3
115,2001,Full Shadow,33.98,26.0,36.1,31.5,41.49,30.2,39.3,33.3,3
116,2002,Full Shadow,36.39,29.7,36.8,33.9,39.54,34.7,41.5,38.2,3
117,2003,Full Shadow,32.79,20.0,30.2,23.8,43.30,32.9,44.8,37.2,3
118,2004,Full Shadow,33.57,24.0,33.1,27.0,47.41,35.9,47.0,39.5,3
119,2005,Full Shadow,37.94,26.2,38.1,30.1,42.31,29.7,40.8,32.3,3
120,2006,Full Shadow,34.83,26.2,33.7,29.8,42.62,34.0,43.8,37.0,3
121,2007,No Shadow,32.41,18.0,26.1,20.1,47.66,32.7,50.1,37.4,1
122,2008,Full Shadow,34.70,25.4,32.1,27.7,41.86,31.6,42.0,35.6,3
123,2009,Full Shadow,36.77,26.2,35.9,29.6,42.87,34.1,45.7,38.2,3
124,2010,Full Shadow,31.80,25.9,28.2,25.8,43.57,39.6,44.6,42.0,3
125,2011,No Shadow,33.04,24.1,34.4,28.6,43.07,33.0,44.2,36.3,1
126,2012,Full Shadow,37.51,30.6,38.6,34.3,50.41,43.4,56.3,47.7,3
127,2013,No Shadow,34.77,25.3,33.4,27.4,40.91,32.7,37.3,33.9,1
128,2014,Full Shadow,32.13,21.0,27.1,22.8,40.51,26.0,38.0,30.3,3
129,2015,Full Shadow,32.99,12.1,23.4,16.1,45.39,27.8,41.6,31.6,3
130,2016,No Shadow,39.47,28.1,36.9,30.8,47.50,38.8,49.5,43.4,1

#### Question 6 - For the remaining rows which have no record (but the other columns *are* populated), determine an appropriate method for inputting the value for this column. Explain your reasoning, and show your work below (using pandas).

In [22]:
print('No Record:',ground_df['Punxsutawney Phil'][ground_df['Punxsutawney Phil'] == 'No Record'].count())
print('No Shadow:',ground_df['Punxsutawney Phil'][ground_df['Punxsutawney Phil'] == 'No Shadow'].count())
print('Partial Shadow:',ground_df['Punxsutawney Phil'][ground_df['Punxsutawney Phil'] == 'Partial Shadow'].count())
print('Full Shadow:',ground_df['Punxsutawney Phil'][ground_df['Punxsutawney Phil'] == 'Full Shadow'].count())

No Record: 6
No Shadow: 15
Partial Shadow: 1
Full Shadow: 100

The following numbers represent the occurrences of Shadow recordings throughought the years. Mathematically the best course of action to replace the 'No Record' values is to use 'Full Shadow' as it will have the least impact to its average as Full Shadow has the highest number of occurrences.

#### Question 7 - If we are trying to write a machine learning program which predicts the type of shadow for the year, which column(s) should be the independent variables X? Why? 

#### Use pandas to assign a variable X to be all of the rows of the data set with the column(s) that represent the independent variables.

In [26]:
X = ground_df[['February Average Temperature', 'February Average Temperature (Northeast)', 
       'February Average Temperature (Midwest)', 'February Average Temperature (Pennsylvania)',
       'March Average Temperature', 'March Average Temperature (Northeast)', 
       'March Average Temperature (Midwest)', 'March Average Temperature (Pennsylvania)']]

These values are considered Independent as they are not affected by the Groundhog's Shadow and in fact effect the event of a Groundhog seeing its shadow.

#### Question 8 - If we are trying to write a machine learning program which predicts the type of shadow for the year, which column(s) should be the dependent variables Y? Why?  

#### Use pandas to assign a variable Y to be all of the rows of the data set with the column(s) that represent the dependent variables.

In [27]:
Y = ground_df['Shadow']

We are predicting the result of a Shadow occurence based on temperture, therefore, the dependent variable is the Shadow column.

#### Question 9 - Using the train_test_split function from the sklearn module, use a 70/30 split validation to split the data set into train and test. If you follow the example at the following link: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

Note: It's common practice to use the following variable names for unpacking the result:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=(YOUR VALUE))

sklearn will create a proper split where the following statements hold true:
X_train is your train set independent variables
Y_train is your train set dependent variables
X_test is your test set independent variables
Y_test is your test set dependent variables

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.30)

#### Question 10 - Should the number of rows in X_train == number of rows in Y_train? Also, should the number of rows in X_test == Y_test? Why or why not? Validate your answer with code below:

In [30]:
X_train.shape[0] == Y_train.shape[0]

True

In [31]:
X_test.shape[0] == Y_test.shape[0]

True